from typing import Any, TypedDict, List
import httpx
from pydantic import BaseModel
from openai import OpenAI
from textwrap import dedent

from ..repositories.labels import Labels, select_labels

class MarkdownContent(TypedDict):
    md_content: str

class MinerUParse(BaseModel):
    backend: str
    version: str
    results: dict[str, MarkdownContent]

class ParseResult(BaseModel):
    full_text: str
    
    structure_info: dict[str, Any]
    
    labels: str
    """Label is generated by llm which format is `science-computer-nlp`"""
    
    metadata: dict[str, Any] | None = None

system_prompt = """你是一名论文标注员。

# 任务描述
给你一篇论文，其中包含标题（title）、摘要（abstract）和引言（introduction），
你需要根据提供的标签列表，为该论文选择合适的标签。

# 可用标签

## 标签格式
-----
main：一级标签，通常表示较大的领域类别。
child：二级标签，属于 main 标签下的子类别。
-----

## 标签列表
{available_labels}

# 标注原则
标签的形式始终为 `Computer Science - Deep Learning - CV` 这种结构。
如你所见，每个标签由三个层级组成，并且层级关系逐级细化。
这三个标签之间使用 `-` 进行连接。

# 输出格式
你只能直接输出标签，不要输出任何其他内容。

# 工作语言
中文
"""



def analyze_with_openclaw(
    file_bytes: bytes, file_name: str, doc_type: str
) -> dict[str, Any]:
    parse_service = ParseService()
    result = parse_service.run(
        file_bytes=file_bytes, file_name=file_name, doc_type=doc_type
    )
    if hasattr(result, "model_dump"):
        return result.model_dump()
    if isinstance(result, dict):
        return dict(result)
    raise ValueError("Parse service returned unsupported result type.")


class ParseService(BaseModel):

    openai_client:OpenAI = OpenAI(base_url="http://localhost:11434/v1", api_key="<EMPTY>")

    model:str = "qwen3:8b"

    class Config:
        arbitrary_types_allowed=True

    def run(self, *, file_bytes: bytes, file_name: str, doc_type: str) -> ParseResult:
        file_name_splits = file_name.split(".")
        with httpx.Client(base_url="http://localhost:8001") as client:
            response = client.post(
                "/file_parse",
                files={
                    "files": file_bytes
                },
                timeout=1000,
            )
            resp = MinerUParse.model_validate(response.json())

            # Get the first index
            first_key = next(iter(resp.results))
            full_text = resp.results[first_key]["md_content"]
        
        labels = self._label(full_text)

        return ParseResult(
            full_text=full_text, 
            structure_info={"name": "yh"},
            labels=labels,
        )
    
    def _label(self, full_text: str):
        repo_labels:List[Labels] = select_labels()
        available_labels = []
        for label in repo_labels:
            name = label.top_label
            child = label.sub_label
            available_labels.append(
                dedent(f"""
                {name}: {",".join(child)}
                """)
            )

        completions = self.openai_client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt.format(available_labels=available_labels)},
                {"role": "user", "content": f"Please label the paper.\n\n{full_text[:3000]}"}
            ]
        )

        response = completions.choices[0].message.content
        if "qwen3" in self.model:
            import re
            response = re.sub(r'<think>.*?</think>', '', response, flags=re.DOTALL)
            response:str = response.strip()

        return response