from typing import Any, TypedDict, List
import httpx
from pydantic import BaseModel
from openai import OpenAI
from textwrap import dedent

from ..repositories.labels import Labels, select_labels

class MarkdownContent(TypedDict):
    md_content: str

class MinerUParse(BaseModel):
    backend: str
    version: str
    results: dict[str, MarkdownContent]

class ParseResult(BaseModel):
    full_text: str
    
    structure_info: dict[str, Any]
    
    labels: str
    """Label is generated by llm which format is `science-computer-nlp`"""
    
    metadata: dict[str, Any] | None = None

system_prompt = """You are a paper annotator.

# Task Description
Give you a paper which contains a title, abstract and introduction,
you will label the paper with the available labels.

# Available labels

## Label format
-----
main: first label. Generally it's a wide type.
child: sub-labels under the main label. 
-----

## Labels
{available_labels}

# Annotation Principle
The label is always like `Computer Science - Deep Learning - CV`.
As you can see, it always consists of three labels. The relationship
of these three labels is detailed progressively. The labels are connected
by `-`.

# Output format
You can and only can output labels directly. Don't output anything else.

# Work language
中文
"""

class ParseService(BaseModel):

    openai_client:OpenAI = OpenAI(base_url="http://localhost:11434/v1", api_key="<EMPTY>")

    model:str = "qwen3:8b"

    class Config:
        arbitrary_types_allowed=True

    def run(self, *, file_bytes: bytes, file_name: str, doc_type: str) -> ParseResult:
        file_name_splits = file_name.split(".")
        with httpx.Client(base_url="http://localhost:8001") as client:
            response = client.post(
                "/file_parse",
                files={
                    "files": file_bytes
                },
                timeout=1000,
            )
            resp = MinerUParse.model_validate(response.json())

            # Get the first index
            first_key = next(iter(resp.results))
            full_text = resp.results[first_key]["md_content"]
        
        labels = self._label(full_text)

        return ParseResult(
            full_text=full_text, 
            structure_info={"name": "yh"},
            labels=labels,
        )
    
    def _label(self, full_text: str):
        repo_labels:List[Labels] = select_labels()
        available_labels = []
        for label in repo_labels:
            name = label.top_label
            child = label.sub_label
            available_labels.append(
                dedent(f"""
                {name}: {",".join(child)}
                """)
            )

        completions = self.openai_client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt.format(available_labels=available_labels)},
                {"role": "user", "content": f"Please label the paper.\n\n{full_text[:3000]}"}
            ]
        )

        # TODO: add checks for llm output in the future.
        
        response = completions.choices[0].message.content
        if "qwen3" in self.model:
            import re
            response = re.sub(r'<think>.*?</think>', '', response, flags=re.DOTALL)
            response:str = response.strip()

        return response