import httpx
import os
from typing import Any, TypedDict, List
from pydantic import BaseModel
from openai import OpenAI
from textwrap import dedent

from ..repositories.labels import Labels, select_labels

MODEL = os.getenv("MODEL")
MINERU_BASE_URL = os.getenv("MINERU_BASE_URL")

class MarkdownContent(TypedDict):
    md_content: str

class MinerUParse(BaseModel):
    backend: str
    version: str
    results: dict[str, MarkdownContent]

class ParseResult(BaseModel):
    full_text: str
    
    structure_info: dict[str, Any]
    
    labels: str
    """Label is generated by llm which format is `science-computer-nlp`"""
    
    metadata: dict[str, Any] | None = None

system_prompt = """你是一名论文标注员。

# 任务描述
给你一篇论文，其中包含标题（title）、摘要（abstract）和引言（introduction），
你需要根据提供的标签列表，为该论文选择合适的标签。

# 可用标签

## 标签格式
-----
main：一级标签，通常表示较大的领域类别。
child：二级标签，属于 main 标签下的子类别。
-----

## 标签列表
{available_labels}

# 标注原则
标签的形式始终为 `Computer Science - Deep Learning - CV` 这种结构。
如你所见，每个标签由三个层级组成，并且层级关系逐级细化。
这三个标签之间使用 `-` 进行连接。

# 输出格式
你只能直接输出标签，不要输出任何其他内容。

# 工作语言
中文
"""


class ParseService(BaseModel):

    model: str = MODEL

    class Config:
        arbitrary_types_allowed = True

    def _get_openai_client(self) -> OpenAI:
        base_url = os.getenv("BASE_URL")
        api_key = os.getenv("DEEPSEEK_API_KEY")
        if not api_key:
            raise ValueError("Missing DEEPSEEK_API_KEY")
        if not base_url:
            raise ValueError("Missing BASE_URL")
        return OpenAI(base_url=base_url, api_key=api_key)

    def run(self, *, file_bytes: bytes, file_name: str, doc_type: str) -> ParseResult:
        if not MINERU_BASE_URL:
            raise ValueError("Missing MINERU_BASE_URL")

        with httpx.Client(base_url=MINERU_BASE_URL) as client:
            response = client.post(
                "/file_parse",
                files={
                    "files": file_bytes
                },
                timeout=1000,
            )
            response.raise_for_status()
            resp = MinerUParse.model_validate(response.json())

            # Get the first index
            first_key = next(iter(resp.results))
            full_text = resp.results[first_key]["md_content"]
        
        labels = self._label(full_text)

        return ParseResult(
            full_text=full_text, 
            structure_info={"name": "yh"},
            labels=labels,
        )
    
    def _label(self, full_text: str):

        repo_labels: List[Labels] = select_labels()
        available_labels = []
        for label in repo_labels:
            name = label.top_label
            child = label.sub_label
            available_labels.append(
                dedent(f"""
                {name}: {",".join(child)}
                """)
            )

        client = self._get_openai_client()
        completions = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt.format(available_labels=available_labels)},
                {"role": "user", "content": f"Please label the paper.\n\n{full_text[:3000]}"}
            ]
        )

        response = completions.choices[0].message.content
        return response
